name       : kparts
version    : 5.58.0
release    : 27
source     :
    - https://download.kde.org/stable/frameworks/5.58/kparts-5.58.0.tar.xz : 6fe1ca552f14dd262cf33e60d0c85536ca04617757e39f91dbfe061abf624bb4
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
