name       : kparts
version    : 5.105.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kparts-5.105.0.tar.xz : ab0033760fcd76d0d156481e026de3b545191b9a3c6cc7e2316fa8c50d95b79c
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
optimize   : lto
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
