name       : kparts
version    : 5.43.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kparts-5.43.0.tar.xz : 8d8b11c5e88ca5c192a527415a841ab4278ec70dd2a766d34c75cdd78d6e2226
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
