name       : kparts
version    : 5.49.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kparts-5.49.0.tar.xz : 53c87663828613d6d64a5a5cdd0c9f2f388ff8191df903c07a4b3f20fd02bf7d
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
