name       : kparts
version    : 5.80.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kparts-5.80.0.tar.xz : 9eb464f171f219e264237bb200767c8b3c70f10004521fad2d90af93bf926eba
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
optimize   : lto
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
