name       : kparts
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kparts-5.41.0.tar.xz : e1ac20ed668efd17d55d92850e57d45d91d909ab8b82549b8e1f4989ec81ad25
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
