name       : kparts
version    : 5.61.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kparts-5.61.0.tar.xz : f223b38f34f009bb25511ce7d97c607102cbb0a1bd0253ec1b7d1fe1b7c81436
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
