name       : kparts
version    : 5.67.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kparts-5.67.0.tar.xz : 0e2c3e4584f9327cb0f4d3b7ffb7e02657fb02ed1b510643a39e6b8cacbda76a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
