name       : kparts
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/kparts-5.36.0.tar.xz : f3e75ac95b1e3c61054cd9140be4b917296f0a666df3487a589cfe055978055e
license    : LGPL-2.1
component  : programming
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
