name       : kparts
version    : 5.107.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kparts-5.107.0.tar.xz : 00b8558644928e4cc1f43de64a74696d038add33895522e085809c9c9a8fa9fb
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
optimize   : lto
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
