name       : kparts
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/kparts-5.32.0.tar.xz : 45e73162459a2f4464fd0e1aeeea34ca03c3e7dbd315eedbb2010cbe5b053d43
license    : LGPL-2.1
component  : programming
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kio-devel
        - ktextwidgets-devel
        - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
